seed: 1
cache: false # caching available only for encoded datasets
use_wandb: false

# Training
multinode: False
batch_size: 4
eval_size: 1024
num_workers: 4
lr: 0.001
lr_schedule: "cosine"
weight_decay: 0.00001
total_steps: 1000
warmup_steps: 100
save_interval: 200
viz_interval: 2000
log_interval: 100
# total_steps: 300000
# warmup_steps: 5000
# save_interval: 2000
# viz_interval: 2000
# log_interval: 100

# Data
data_path: "/raid/moving_mnist_long_1"
eval_seq_len_1: 10
eval_seq_len_2: 20
seq_len: 30
image_size: 64
channels: 1

num_shards: null
rng_keys: ["dropout", "sample"]
batch_keys: ["video", "actions"]

# Model
model: "convS5_noVQ"

loss_weight: 0.5

order_prediction: false
# encoder_type: "tubelet"
encoder: # encoder / decoder are mirrored, with decoder depths reversed
  depths: [8, 16, 32] # 64x64 to 16x16
  blocks: 1 #blocks doesn't do anything here
  num_groups: 8

decoder: # encoder / decoder are mirrored, with decoder depths reversed
  depths: [8, 16, 32] # 16x16 to 64x64
  blocks: 1
  num_groups: 8

d_model: 32

# Sequence Model
seq_model:
  n_layers: 8
  layer_activation: "gelu"
  dropout: 0.0
  use_norm: True
  prenorm: False
  per_layer_skip: True
  num_groups: 8
  squeeze_excite: False
  skip_connections: False

# SSM
ssm:
  ssm_size: 64
  blocks: 1
  clip_eigs: True
  B_kernel_size: 3
  C_kernel_size: 3
  D_kernel_size: 3
  dt_min: 0.001
  dt_max: 0.1
  C_D_config: "resnet"


latent_height: 16
latent_width: 16

n_cond: 1
drop_loss_rate: 0.0

causal_masking: False

# Actions
use_actions: False
action_dim: 1
action_embed_dim: 1
dropout_actions: False
action_dropout_rate: 0.0
action_mask_id: -1

# Sampling
open_loop_ctx: 10

open_loop_ctx_1: 10
action_conditioned_1: False
open_loop_ctx_2: 10
action_conditioned_2: False